persistent autoUpgrade

diff --git a/.github/workflows/auto-version-bump.yaml b/.github/workflows/auto-version-bump.yaml
--- a/.github/workflows/auto-version-bump.yaml
+++ b/.github/workflows/auto-version-bump.yaml
@@ -13,15 +13,38 @@ jobs:
       uses: actions/checkout@v3
 
     - name: Setup Nix
-      uses: cachix/install-nix-action@v16
+      uses: cachix/install-nix-action@v22
 
-    - name: Update Flake
-      run: |
-        nix flake update
-        if nix flake check; then
+  update_flake:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Update Flake
+        run: nix flake update
+
+  check_flake:
+    needs: update_flake
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Flake
+        run: |
+          if nix flake check; then
+            echo "Flake is valid."
+          else
+            echo "Flake is invalid."
+            exit 1
+          fi
+
+  commit_changes:
+    needs: check_flake
+    runs-on: ubuntu-latest
+    steps:
+      - name: Configure Git
+        run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
-          git add flake.lock
-          git commit -m "automated daily version bump"
-          git push
-        fi
+      - name: Stage changes
+        run: git add flake.lock
+      - name: Commit changes
+        run: git commit -m "Automated daily version bump"
+      - name: Push changes
+        run: git push
